Ajout de la gestion de la vitesse dans le composant Animals_card et c…
WildCodeSchool-2024-09/JS-RemoteFR-Vendangeurs-P2-Marmelade pull request #46
Opened 2024-11-20 16:03 UTC by MateuszPlebanek

_Ajout de la propriété vitesse_kmhdans le composant Animals_card.
_Ajustement des types pour inclure vitesse_kmh.
_Correction du formatage du fichier.

2024-11-20 16:37 UTC, Brian-boudrioux requested changes
Erreur de linter :
src/components/Game_zone/Game_zone.tsx(37,19): error TS2741: Property 'vitesse_kmh' is missing in type 'AnimalType'

Comme tu as rajouter une propriété vitesse_kmh dans ton interface animal_cardProps il faut que tu rajoute cette propriété aussi dans AnimalType qui est dans ton composant GameZone

2024-11-20 20:28 UTC, Leslaures approved these changes
ok

2024-11-21 13:31 UTC, Marvin97120 approved these changes
nice

2024-11-21 13:32 UTC, MateuszPlebanek commented
@Brian-boudrioux ( c'est ok pour la pr c'est modifié)

2024-11-21 15:37 UTC, Brian-boudrioux approved these changes

2024-11-21 15:37 UTC, merged